In [2]:
import numpy as np

 # Create a rank 1 array
 # Prints "<class 'numpy.ndarray'>"
 # Prints "(3,)"
 # Prints "1 2 3"
 # Change an element of the array
 # Prints "[5, 2, 3]"

 # Create a rank 2 array
 # Prints "(2, 3)"
 # Prints "1 2 4"

In [3]:
a = np.array([1,2,3])

In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
a.shape

(3,)

In [10]:
print(a[0],a[1],a[2])

1 2 3


In [11]:
a[0] = 5

In [12]:
print(a)

[5 2 3]


In [14]:
b = np.array([[1,2,3],[4,5,6]])

In [15]:
b.shape

(2, 3)

In [16]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [17]:
# Create an array of all zeros
# Prints "[[ 0.  0.]
#          [ 0.  0.]]"

# Create an array of all ones
# Prints "[[ 1.  1.]]"

# Create a constant array
# Prints "[[ 7.  7.]
#          [ 7.  7.]]"

# Create a 2x2 identity matrix
# Prints "[[ 1.  0.]
#          [ 0.  1.]]"

# Create an array filled with random values
# Might print "[[ 0.91940167  0.08143941]
#               [ 0.68744134  0.87236687]]"

In [19]:
a = np.zeros([2,2])
print(a)

[[0. 0.]
 [0. 0.]]


In [21]:
a = np.ones([1,2])
print(a)

[[1. 1.]]


In [24]:
a = np.full([2,2],7)
print(a)

[[7 7]
 [7 7]]


In [26]:
a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [29]:
a = np.random.random([2,2])
print(a)

[[0.27190802 0.68517087]
 [0.48453605 0.45638341]]


In [30]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
# Rank 1 view of the second row of a
# Rank 2 view of the second row of a
 # Prints "[5 6 7 8] (4,)"
 # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:


# Prints "[ 2  6 10] (3,)"
# Prints "[[ 2]
#          [ 6]
#          [10]] (3, 1)"

In [32]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [36]:
b = a[1,:]
print(b, b.shape)

[5 6 7 8] (4,)


In [35]:
c = a[1:2,:]
print(c, c.shape)

[[5 6 7 8]] (1, 4)


In [37]:
d = a[:,1]
print(d,d.shape)

[ 2  6 10] (3,)


In [38]:
e = a[:,1:2]
print(e,e.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [40]:
# An example of integer array indexing.
# The returned array will have shape (3,) and
 # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
 # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
 # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
 # Prints "[2 2]"

In [42]:
a = np.array([[1,2],[3,4],[5,6]])

In [43]:
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [46]:
print(np.array( [ a[0,0],a[1,1],a[2,0] ] ) )

[1 4 5]


In [47]:
print(a[[0,0],[1,1]])

[2 2]


In [50]:
print(np.array([a[0,1],a[0,1]]))

[2 2]


In [51]:
# Create a new array from which we will select elements


# prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices


# Select one element from each row of a using the indices in b
 # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b


 # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

In [54]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
b = np.array([0,2,0,1])

In [56]:
a[np.arange(4),b]

array([ 1,  6,  7, 11])

In [57]:
a[np.arange(4), b] += 10

In [58]:
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [59]:

 # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

  # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
   # Prints "[3 4 5 6]"

In [60]:
a = np.array([[1,2],[3,4],[5,6]])

In [61]:
bool_index = a > 2

In [63]:
print(a[bool_index])

[3 4 5 6]


In [64]:
print(a[a>2])

[3 4 5 6]


In [65]:
# Let numpy choose the datatype
# Prints "int64"

# Let numpy choose the datatype
# Prints "float64"

# Force a particular datatype
# Prints "int64"

In [66]:
a = np.array([1,2])
a.dtype

dtype('int64')

In [67]:
a = np.array([1.0,2.0])
a.dtype

dtype('float64')

In [69]:
a = np.array([1.0,2.0], dtype = np.int64)
print(a, a.dtype)

[1 2] int64


In [70]:
# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]


# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]


# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]


# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]


In [72]:
a = np.array([[1,2],[3,4]], dtype=np.float64)
b = np.array([[5,6],[7,8]], dtype=np.float64)

In [78]:
print(a + b)
print(np.add(a,b))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [79]:
print(a-b)
print(np.subtract(a,b))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [80]:
print(a*b)
print(np.multiply(a,b))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [81]:
print(a/b)
print(np.divide(a,b))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [82]:
np.sqrt(a,b)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [83]:

# Inner product of vectors; both produce 219


# Matrix / vector product; both produce the rank 1 array [29 67]


# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]


In [86]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.array([9,10])
d = np.array([11,12])

In [87]:
np.dot(c,d)

219

In [88]:
np.dot(a,c)

array([29, 67])

In [93]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [95]:
x = np.array([[1,2],[3,4]])

 # Compute sum of all elements; prints "10"
 # Compute sum of each column; prints "[4 6]"
 # Compute sum of each row; prints "[3 7]"

In [96]:
np.sum(x)

10

In [97]:
np.sum(x,axis=0)

array([4, 6])

In [98]:
np.sum(x,axis=1)

array([3, 7])

In [99]:
 # Prints "[[1 2]
            #          [3 4]]"
# Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:

 # Prints "[1 2 3]"
# Prints "[1 2 3]"

In [100]:
a = np.array([[1,2],[3,4]])
b = np.array([1,2,3])

In [102]:
print(a)
print(a.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [103]:
print(b)
print(b.T)

[1 2 3]
[1 2 3]


In [125]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y = np.array([1,0,1])
z = np.empty_like(x)

In [126]:
for i in range(4):
    z[i,:] = x[i,:] + y

print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [127]:
yy = np.tile(y,(4,1))

In [128]:
np.add(x,yy)

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [129]:
x + y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])